/**
 * File: ChartRenderer.tsx
 * Version: 1.1.0
 * Created At: 2026-04-25
 * Updated At: 2026-04-29
 * Description: Client-side visualization component. Dynamically loads Plotly.js 
 *              to render interactive charts generated by the AI backend.
 */

'use client';

import dynamic from 'next/dynamic';
import type { ChartSpec } from '@/lib/types';

/**
 * Plotly is a heavy, browser-only library. 
 * We use Next.js dynamic imports to prevent SSR crashes and optimize bundle size.
 */
const Plot = dynamic(() => import('react-plotly.js').then((m) => m.default), {
  ssr: false,
  loading: () => (
    <div className="h-64 flex items-center justify-center text-muted-foreground animate-pulse">
      Initialising visualisation engine…
    </div>
  ),
});

interface Props {
  /** The standardized chart specification from the backend. */
  spec: ChartSpec;
}

/**
 * ChartRenderer Component
 * 
 * Takes a backend-generated Plotly specification and applies the global 
 * "glassmorphism" theme and responsive handlers.
 */
export function ChartRenderer({ spec }: Props) {
  return (
    <div className="bg-muted/10 border border-border/50 rounded-lg p-4 overflow-hidden backdrop-blur-sm shadow-xl">
      <Plot
        data={spec.data as any}
        layout={{
          ...spec.layout,
          autosize: true,
          paper_bgcolor: 'transparent',
          plot_bgcolor: 'transparent',
          font: { color: '#e6e9f0', size: 12, family: 'Inter, sans-serif' },
          margin: { t: 40, r: 20, b: 40, l: 40 },
          // Enhanced visual styling for dark mode compatibility
          xaxis: { gridcolor: 'rgba(255,255,255,0.05)', zerolinecolor: 'rgba(255,255,255,0.1)' },
          yaxis: { gridcolor: 'rgba(255,255,255,0.05)', zerolinecolor: 'rgba(255,255,255,0.1)' },
        }}
        useResizeHandler
        style={{ width: '100%', height: '360px' }}
        config={{ 
          displaylogo: false, 
          responsive: true,
          modeBarButtonsToRemove: ['sendDataToCloud' as any, 'editInChartStudio' as any] 
        }}
      />
    </div>
  );
}
