/**
 * File: SqlBlock.tsx
 * Version: 1.1.0
 * Created At: 2026-04-25
 * Updated At: 2026-04-29
 * Description: A collapsible, syntax-styled code block for SQL statements.
 *              Allows users to audit the AI-generated queries and copy 
 *              them to the clipboard for manual execution.
 */

'use client';

import { ChevronDown, ChevronRight, Copy, Check } from 'lucide-react';
import { useState } from 'react';

interface Props {
  /** The raw SQL string generated by the LLM pipeline. */
  sql: string;
}

/**
 * SqlBlock Component
 * 
 * Provides a low-profile, expandable interface for viewing and copying SQL.
 * Keeping the SQL behind a collapse toggle ensures the UI remains focused 
 * on insights and data.
 */
export function SqlBlock({ sql }: Props) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  /**
   * Safely writes the SQL text to the system clipboard.
   * Includes a temporary "Copied" feedback state.
   */
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      /* Silently fail if clipboard permissions are denied */
    }
  };

  return (
    <div className="bg-muted/10 border border-border/50 rounded-lg text-[12px] backdrop-blur-sm overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between gap-2 px-4 py-2.5 text-muted-foreground hover:text-foreground transition-colors group"
      >
        <div className="flex items-center gap-2">
          {open ? (
            <ChevronDown className="w-3.5 h-3.5 text-primary" />
          ) : (
            <ChevronRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
          )}
          <span className="font-medium">Audit Generated SQL</span>
        </div>
        <span className="text-[10px] uppercase tracking-widest opacity-40">Security Verified</span>
      </button>

      {open && (
        <div className="border-t border-border/30 bg-black/20">
          <div className="flex justify-end px-3 py-1.5">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground bg-muted/20 hover:bg-muted/40 px-2 py-1 rounded transition-all active:scale-95"
            >
              {copied ? (
                <>
                  <Check className="w-3 h-3 text-green-500" />
                  <span className="text-green-500">Copied</span>
                </>
              ) : (
                <>
                  <Copy className="w-3 h-3" />
                  <span>Copy</span>
                </>
              )}
            </button>
          </div>
          <pre className="font-mono text-foreground/80 px-4 pb-4 overflow-x-auto whitespace-pre-wrap leading-relaxed selection:bg-primary/30">
            {sql}
          </pre>
        </div>
      )}
    </div>
  );
}
