"""
File: errors.py
Version: 1.1.0
Created At: 2026-04-25
Updated At: 2026-04-29
Description: Standardized exception hierarchy for the ConnectDB AI ecosystem. 
             Provides user-safe error messages, actionable hints, and stage tracking 
             for the end-to-end chat pipeline.
"""

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse


class ConnectDBError(Exception):
    """
    Base domain exception for the application.
    
    Attributes:
        status_code: Suggested HTTP status code for the response.
        stage: The specific part of the pipeline where the error occurred 
               (e.g., 'connect', 'sql_guard', 'llm').
    """
    status_code: int = 400
    stage: str = "unknown"

    def __init__(self, message: str, *, hint: str | None = None, stage: str | None = None):
        """
        Args:
            message: Internal developer-focused error message.
            hint: User-friendly message explaining how to fix the issue.
            stage: Pipeline marker for UI tracking.
        """
        super().__init__(message)
        self.message = message
        self.hint = hint or message
        if stage:
            self.stage = stage


class ConnectionFailed(ConnectDBError):
    """Raised when initial database connectivity or introspection fails."""
    status_code = 400
    stage = "connect"


class SessionNotFound(ConnectDBError):
    """Raised when a request is made for an expired or non-existent session."""
    status_code = 404
    stage = "session"


class UnsafeSQLError(ConnectDBError):
    """Raised when the SQL generated by the LLM fails security validation."""
    status_code = 422
    stage = "sql_guard"


class SQLExecutionError(ConnectDBError):
    """Raised when valid SQL encounters a runtime error (e.g., timeout, syntax)."""
    status_code = 400
    stage = "execute"


class LLMProviderError(ConnectDBError):
    """Raised when an external LLM provider returns an error (e.g., API key, rate limit)."""
    status_code = 502
    stage = "llm"


def register_exception_handlers(app: FastAPI) -> None:
    """
    Global exception handler registration for FastAPI.
    Intercepts ConnectDBError and returns a standardized JSON error response.
    """
    @app.exception_handler(ConnectDBError)
    async def _handle(request: Request, exc: ConnectDBError):
        return JSONResponse(
            status_code=exc.status_code,
            content={
                "error": {
                    "stage": exc.stage,
                    "message": exc.message,
                    "hint": exc.hint,
                }
            },
        )
